# Site settings
title: MLStudio
description: "ML, DL, Optimal Control Theory Blog"
url: "https://edmophia.github.io/"
author:
  name: "Sung-Yub Kim"
  email: "edmophia@snu.ac.kr"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
highlighter: rouge
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
